#!/bin/bash
#=============================================================================
# Check iso3166-1_en_sentence_case.csv against the official ISO3166-1 list
#
# Author:  Seth Fischer
#=============================================================================

ISO3166_1_DB="iso3166-1_en.csv"
ISO3166_SENTENCE_CASE_DB="iso3166-1_en_sentence_case.csv"

# compare official ISO3166-1 alpha-2 codes with sentence case alpha-2 codes

diff \
--side-by-side \
--suppress-common-lines \
--strip-trailing-cr \
<(tail -n +2 $ISO3166_1_DB | cut -d';' -f2 | sort) \
<(tail -n +2 $ISO3166_SENTENCE_CASE_DB | cut -d';' -f1 | sort)

exit

